version: 2
updates:
  - package-ecosystem: "gomod"
    open-pull-requests-limit: 9999
    # directory: "/bar"
    directory: "/"
    schedule:
      interval: "daily"
# #    allow:
# #      - dependency-type: indirect
#   - package-ecosystem: "gomod"
#     open-pull-requests-limit: 9999
#     directory: "/foo"
#     schedule:
#       interval: "daily"
# #    allow:
# #      - dependency-type: indirect
